# Generated by Django 5.0 on 2024-07-25 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='service_seconds',
            new_name='survive_seconds',
        ),
    ]
