# Generated by Django 5.0 on 2024-07-25 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoreboard', '0002_rename_service_seconds_score_survive_seconds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='survive_seconds',
            new_name='service_seconds',
        ),
    ]
